### ISSUE TITLE
扫描二维码的相关问题

### ISSUE THREAD

**Issue by lihaicheng** [huangfangyi/FanXin#7]
我认为com.fanxin.huangfangyi.main.widget.zxing.activity.CaptureActivity是二维码的扫描界面，如果不是请大神指正。其中handleDecode为什么没有被调用。难道扫描这一部分没做完吗？

**Comment by chitianfarmer** [comment]
这个项目中用到的是https://github.com/huangfangyi/FanXin/blob/master/src/com/fanxin/huangfangyi/main/activity/ScanCaptureActivity.java 这个页面 没有使用com.fanxin.huangfangyi.main.widget.zxing.activity.CaptureActivity

**Comment by lihaicheng** [comment]
这样就是说作者放弃了zxing插件，自己实现了扫描二维码的业务是吗？
